FROM php:7.2.9-fpm-alpine3.8

ENV PHPIZE_DEPS \
	autoconf \
	g++ \
	make \
	libxml2-dev \
	pcre-dev
	gcc \
	openssl-dev \
	hiredis-dev \
	nghttp2-dev

RUN set -xe \
	&& echo 'http://mirrors.aliyun.com/alpine/v3.8/main/' > /etc/apk/repositories \
	&& apk add --no-cache --virtual .build-deps \
	$PHPIZE_DEPS \
	&& docker-php-source extract \
\
\
RUN cd /usr/src \
	&& ( \
		cd /usr/src/php/ext/sockets \
		&& phpize \
		&& ./configure --enable-sockets \
		&& make && make install \
		&& docker-php-ext-enable sockets \
	) \
	&& ( \
		cd /usr/src/php/ext/openssl \
		&& phpize \
		&& ./configure --enable-openssl \
		&& make && make install \
		&& docker-php-ext-enable openssl \
	) \
	&& cd /usr/src \
	&& curl -fsSL 'https://github.com/swoole/swoole-src/archive/master.tar.gz' -o swoole.tar.gz \
	&& mkdir -p swoole \
	&& tar -xf swoole.tar.gz -C swoole --strip-components=1 \
	&& rm swoole.tar.gz \
	&& ( \
		cd swoole \
		&& phpize \
		&& ./configure \
		--enable-coroutine \
		--enable-openssl \
		--enable-http2 \
		--enable-async-redis \
		--enable-sockets \
		--enable-mysqlnd \
		&& make && make install \
		&& cd ../ \
	) \
	&& rm -r swoole \
	&& docker-php-ext-enable swoole \
\
&& apk del .build-deps \
&& pecl update-channels \
&& rm -rf /tmp/pear ~/.pearrc \
&& cd / \
&& docker-php-source delete
